############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
weight = 4
name = "Services Offered"

[[main]]
parent = "Services Offered"
name = "Virus and Malware Removal"
url = "/virusremoval"

[[main]]
parent = "Services Offered"
name = "Data Recovery"
url = "/datarecovery"

[[main]]
parent = "Services Offered"
name = "Hardware Upgrades and Replacement"
url = "/hardware"

[[main]]
parent = "Services Offered"
name = "Software Installation and Troubleshooting"
url = "/software"

[[main]]
parent = "Services Offered"
name = "Networking Setup and Support"
url = "/networking"

[[main]]
parent = "Services Offered"
name = "Custom-Built Computers"
url = "/custombuilt"

[[main]]
name = "Remote Support"
url = "/remote"
weight = 5

[[main]]
name = "Service Area"
url = "/servicearea"
weight = 6

[[main]]
name = "Contact"
url = "/contact"
weight = 7

[[main]]
name = "Pricing"
url = "/pricing"
weight = 8

[[main]]
name = "Testimonials"
url = "/testimonials"
weight = 9

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1


[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 9

[[main]]
name = "Remote Support"
url = "/remote"
weight = 5

[[main]]
name = "Service Area"
url = "/servicearea"
weight = 6

[[main]]
name = "Contact"
url = "/contact"
weight = 7

[[main]]
name = "Pricing"
url = "/pricing"
weight = 8
